### ISSUE TITLE
Multi-Store

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#37]
- [ ] Product types become multi-store/site aware #39 #157 #37 #382
- [ ] Variant should also be localized? #167
- [ ] Localized (translatable) description of discount/sale/shipping method #199 #457 
- [ ] Pricing is per site/ per store #93 
- [ ] Store settings become store specific #1681
- [ ] Store specific sales #2053

**Comment by pdaleramirez** [comment]
Do you have ETA of the release for this feature? i kinda waiting on this for my project.

**Comment by lukeholder** [comment]
We don't have a specific ETA @pdaleramirez sorry. Won't be in 3.x but maybe will in 4.x

**Comment by pdaleramirez** [comment]
Looking forward to 4.x

**Comment by AndrewMac-UTS** [comment]
I'm afraid that although I too am 'looking forward' to this, I seriously cannot wait. I have a project coming up where this is a core requirement, so it looks like I'm going to have to use some other CMS. 

This has been around a long time now. Please please please make sure it makes it into 4.0 ... please ;-)

**Comment by stevenjwright** [comment]
+1 for me on this. Currently handling this with 4 sites in one install (same client company) making use of permissions and product types to separate CP usage and  using some custom reports for orders... not ideal, but making do for now!

**Comment by mariovass** [comment]
+1

**Comment by mark-chief** [comment]
Project in the pipeline for this requirement, really don’t want to use anything else but Craft + Commerce. Thanks.

**Comment by jripmeester** [comment]
+1

**Comment by jordanhammond** [comment]
Choosing an ecommerce CMS now for 4+ website domains using the same ERP. Will require all of the features described in the description. +1 to prioritise this.

**Comment by jordanhammond** [comment]
> I'm afraid that although I too am 'looking forward' to this, I seriously cannot wait. I have a project coming up where this is a core requirement, so it looks like I'm going to have to use some other CMS.
> 
> This has been around a long time now. Please please please make sure it makes it into 4.0 ... please ;-)

@AndrewMac-UTS did you find another CMS product that delivered these requirements?

**Comment by frbron** [comment]
+1

**Comment by ArtDepartmentMJ** [comment]
+1

**Comment by edwardpmartinez** [comment]
+1

**Comment by boboldehampsink** [comment]
+1

**Comment by bhuvidya** [comment]
+1

**Comment by tigerchick** [comment]
That this hasn't yet made it into Commerce seems to be in contradiction to the "core concepts" docs: https://craftcms.com/docs/commerce/3.x/core-concepts.html

"Because Craft Commerce is built on Craft CMS, most Craft features can be integral to the ecommerce experience:
...
- Localization...."

Looking forward to this being addressed.
